#define CALIBRATION_ERROR 1000
#define CALBIRATION_SENSOR_TOO_FAR CALIBRATION_ERROR + 1
#define CALBIRATION_SENSOR_TOO_CLOSE CALIBRATION_ERROR + 2

#define MEASURE_ERROR 2000
#define MEASURE_SENSOR_TOO_FAR CALIBRATION_ERROR + 1
#define MEASURE_SENSOR_TOO_CLOSE CALIBRATION_ERROR + 2